### ISSUE TITLE
Quotes Don't Always Auto Rotate 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#100]
When I refresh the page and scroll down to the quotes section they do not always auto rotate. 

@L8D Can you recreate the issue?

**Comment by L8D** [comment]
@Ryan-Parker I can reproduce, though incredibly inconsistently. This will likely be a long-standing bug

**Comment by Ryan-Parker** [comment]
@L8D Its happening fairly frequently for me now, as I don't see them rotating at all. I was viewing in Incognito Chrome

**Comment by L8D** [comment]
@Ryan-Parker could you record a screencast of the issue? And how you're reproducing it?

**Comment by Ryan-Parker** [comment]
@L8D Sure no problem let me get that to you while we work on the the other issues at hand

**Comment by Ryan-Parker** [comment]
@L8D Looking at this again the carousel seems to get stuck on Karolina.

**Comment by L8D** [comment]
This happens with the user holds their cursor over the carousel
