### ISSUE TITLE
Change Anchored Nav Logo

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#103]
The logo should be changed in the anchored nav.

**Comment by Ryan-Parker** [comment]
It should be the black logo like in the designs

![screen shot 2015-06-01 at 7 50 20 pm](https://cloud.githubusercontent.com/assets/7152379/7925818/80a7676c-0897-11e5-8ba5-949bfa2ef1b8.png)

**Comment by L8D** [comment]
Yep. Waiting on Natalie for the logo since the dropbox link is invalid

**Comment by Ryan-Parker** [comment]
She had sent a deliverable zip over today via email. Was it not in that package?

**Comment by L8D** [comment]
Ah. I missed the email. Will fix soon
