### ISSUE TITLE
Anchored Nav Transition Incorrect 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#104]
Right now when you scroll down the page on panel 1 the nav does not follow you until you reach the end of the panel and the white background comes out from below the first image. This is incorrect

![screen shot 2015-05-28 at 9 44 24 am](https://cloud.githubusercontent.com/assets/7152379/7861462/538264ca-051e-11e5-9644-86bcd703ef05.png)

It should instead function like http://usepanda.com/. Where the nav follows you down the screen from the beginning and the white background comes in above the first panel.

**Comment by GarrethDottin** [comment]
Style guide now reflects hover states:
https://projects.invisionapp.com/share/422BZ1OQ7#/screens/72267451?maintainScrollPosition=false

**Comment by L8D** [comment]
Did we confirm this with the design team or is this a feature you really prefer? To be honest, I think the way it is currently done looks more professional, and doesn't use any JavaScript to obtain the effect.

If you want a fixed (not anchored/sticky) navigation bar, I can change it to be that way, however I would need to use JavaScript to perform checks during scrolling. That would make scrolling that-much-more jittery on mobile (not to mention what happens when the URL bar hides and shows).

You'll notice how https://usepanda.com disables the transitional navigation bar for mobile screens. I could try to do the same, but it still feels unfortunate that I'd have to do it in the first place.

**Comment by Ryan-Parker** [comment]
@L8D I do think that the way it functions now is not standard and feels a bit off. I would also be open to it functioning like https://www.worklife.com/. Would that be a possibility without the use of JavaScript?

**Comment by L8D** [comment]
@Ryan-Parker actually that should be very do-able without JavaScript. Let me see what I can do

**Comment by L8D** [comment]
I just figured out something that would allow me to do the fixed-transitional version with ease.

**Comment by Ryan-Parker** [comment]
@L8D Can we have the white background come in above the image of the girl instead of coming out from behind?

**Comment by L8D** [comment]
So you don't want any transition?

**Comment by Ryan-Parker** [comment]
@L8D Do you notice how on http://usepanda.com/ the black transparent background comes in from the top instead of coming out from below the main hero image?

**Comment by L8D** [comment]
@Ryan-Parker Are you referring to the transition animation? I can do that though it would require JavaScript. It doesn't resolve the problem we have for mobile devices, where the navbar text collides with the hero text.

I would recommend just putting a darkened background behind the navbar in the first panel, so when scrolling through it the text doesn't collide.

**Comment by Ryan-Parker** [comment]
@L8D Let me regroup with @GarrethDottin on this issue, as I worry that will impact the design of the page.

**Comment by L8D** [comment]
When I said we should put a darkened background I meant to add "for mobile screens." To demonstrate the issue:

Here's how was before (or is now):

![screenshot_2015-06-03-17-47-47](https://cloud.githubusercontent.com/assets/2355315/7973268/4eb7f022-0a19-11e5-87d6-04cde7128ea1.png)

Here's what I recommending: (only seen on mobile screens)

![screenshot_2015-06-03-17-48-30](https://cloud.githubusercontent.com/assets/2355315/7973269/5013ddaa-0a19-11e5-97bb-92dc4a659404.png)

The background could be darker though

**Comment by Ryan-Parker** [comment]
@L8D Oh yes I see now. Let us discuss this before we make a final decision.
