### ISSUE TITLE
Put everything behind Login

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#105]
There should be redirects instituted so that users cannot access parts of the site without authentication.

**Comment by garrethdev** [comment]
When the user logs in, leaves the site, and then comes back to the site there is no check to see if the user is already logged in.

**Comment by L8D** [comment]
That has nothing to do with 'Put everything behind login' and everything to do with how the routes are configured. If the user revisits the site under '/app', which is where the dashboard is, then the dashboard will load.

Pedantic notes aside, this is almost done.
