### ISSUE TITLE
Buttons and links broken on landing page 

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#107]
Currently the buttons for the following are not working. 
  -Login top right corner
  -Login fixed Nv
  -Get Started in the 1st panel 
  -Get Started in the last panel

**Comment by Ryan-Parker** [comment]
Final button still not linking correctly: 

![screen shot 2015-06-01 at 9 18 41 pm](https://cloud.githubusercontent.com/assets/7152379/7926675/e87205d0-08a3-11e5-81c4-440a70d5d56d.png)
