### ISSUE TITLE
When Time is Up Task Should Display "Ended" 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#109]
When time is up the task should say "Ended" instead of in progress. 

Current: 
![screen shot 2015-06-02 at 1 55 18 pm](https://cloud.githubusercontent.com/assets/7152379/7942898/2ac41e42-092f-11e5-8ffa-b758dbdfa35e.png)

Design: 
![screen shot 2015-06-02 at 1 55 47 pm](https://cloud.githubusercontent.com/assets/7152379/7942903/316c33d8-092f-11e5-8ea2-85aaf9800ed1.png)

**Comment by Ryan-Parker** [comment]
@L8D The change from "In Progress" to "Ended" seems to be delayed after the time is completed. Are you noticing that?

**Comment by L8D** [comment]
@Ryan-Parker good catch. I wasn't thinking about needing to live-update the data. Will fix soon

**Comment by Ryan-Parker** [comment]
Looking good @L8D thanks for the quick fix.
