### ISSUE TITLE
Remove Video on Mobile, Replace with Static Image

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#110]
Remove the video capability on mobile and have it just be a static image of the platform. Right now if you play the video it defaults to the quicktime player on iphone and overtakes the screen. 

![image1 15](https://cloud.githubusercontent.com/assets/7152379/7944021/3ae8bd08-0936-11e5-8c90-7999ba141a33.PNG)

**Comment by L8D** [comment]
Can't reproduce on an Android phone

**Comment by Ryan-Parker** [comment]
This is on an iphone 6 which uses quicktime. Do you have browser stack? If not I can provide our credentials so you can test.

**Comment by L8D** [comment]
Wait sorry... Wrong issue.

**Comment by Ryan-Parker** [comment]
@L8D This is still an issue even viewing withing PR 229
