### ISSUE TITLE
Carousel Not Showing 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#112]
The carousel is now showing on mobile. This was working perviously. Might be something with the most recent push.

![image2 3](https://cloud.githubusercontent.com/assets/7152379/7944086/a18b1c9a-0936-11e5-8453-a4ed0ec30aba.PNG)

**Comment by L8D** [comment]
Can't reproduce on an Android phone. I would need access to an iOS device or a screencast to further examine.

**Comment by Ryan-Parker** [comment]
@L8D We are looking into this for you.

**Comment by Ryan-Parker** [comment]
@L8D Just noticed that it works on Safari IOS but not Chrome.

**Comment by L8D** [comment]
Can't reproduce on an iPhone 6 in the latest versions of Safari or Chrome (as of June 3rd):

![download_20150603_142016](https://cloud.githubusercontent.com/assets/2355315/7969391/219be214-09fc-11e5-9464-d909215953dc.jpeg)
![download_20150603_142022](https://cloud.githubusercontent.com/assets/2355315/7969393/23bd6fcc-09fc-11e5-8416-a954f29f54f2.jpeg)

**Comment by Ryan-Parker** [comment]
@L8D This seems to be resolved now.
