### ISSUE TITLE
Center Text & Button Vertically

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#113]
Center the text & button vertically on mobile. Right now its too low. 

![image1 16](https://cloud.githubusercontent.com/assets/7152379/7944170/13e665d8-0937-11e5-80cb-e51d3bbb98f2.PNG)

**Comment by L8D** [comment]
This isn't what I interpreted from the wireframes. The text shouldn't cover the face of the woman in the background.

**Comment by Ryan-Parker** [comment]
Agree that we should see her face. But I think we do need to move it up a bit more to a little below the chin.
