### ISSUE TITLE
Add Inspectlet Analytics

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#124]
Login information for inspectlet should be in our account. Add to codebase so we can view how people interact with the social feed

**Comment by L8D** [comment]
closed by 911ffb8fb8ad09b55b276c278b51d8ef3b091784

**Comment by garrethdev** [comment]
Need to verify on Monday whether this is working

**Comment by garrethdev** [comment]
@L8D  Unclear whether this is working. I've reached out to the company but if by Tuesday this isn't working we need to find alternative sources.
