### ISSUE TITLE
UI Notification System 

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#133]
Notification toaster messages should reflect UI in new designs

**Comment by Ryan-Parker** [comment]
I am not seeing this reflected. Current approved UI below. 

Designs: 
![screen shot 2015-07-06 at 4 16 57 pm](https://cloud.githubusercontent.com/assets/7152379/8532216/906b8650-23fa-11e5-8ec6-0cdda1fd8113.png)

Current: 
![screen shot 2015-07-06 at 5 22 06 pm](https://cloud.githubusercontent.com/assets/7152379/8533527/bf39b23c-2403-11e5-8874-fca5144f93df.png)
