### ISSUE TITLE
Overlapping Newsfeed Issue

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#143]
Currently when a task in the newsfeed is leaving it overlaps with the new task in the newsfeed. It happens once every 5 minutes or so.

**Comment by ZambiBambi** [comment]
Still a problem on safari versions 7 & 8

Safari 7
![bs_macmav_safari_7 0 1](https://cloud.githubusercontent.com/assets/13108339/8559188/73e178d8-254d-11e5-92c1-312a0b9acce8.jpg)

Safari 8
![bs_macyos_safari_8 0 2](https://cloud.githubusercontent.com/assets/13108339/8559196/87261296-254d-11e5-82ca-ff173cede773.jpg)

**Comment by L8D** [comment]
Stupid safari, not supporting the browser visibility API

**Comment by Ryan-Parker** [comment]
@L8D I am still noticing this as an issue. When the newsfeed changes tasks it will overlap for a couple seconds before correcting itself
