### ISSUE TITLE
Complete Task not working

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#144]
A User cannot hit complete task when they finish. The task merely stays populated and no UI changes happen.

**Comment by ZambiBambi** [comment]
Still has the problem in Firefox, Cant test on safari as it wont even load the app
![bs_win7_firefox_38 0](https://cloud.githubusercontent.com/assets/13108339/8538800/8e767b82-24b5-11e5-9f65-d30d3a84761f.jpg)
![bs_win7_safari_5 1 2](https://cloud.githubusercontent.com/assets/13108339/8538801/917de108-24b5-11e5-9201-243a016b4fde.jpg)

**Comment by Ryan-Parker** [comment]
@ZambiBambi What version of Safari are you using? It seems to be working fine for me in my browser

**Comment by ZambiBambi** [comment]
@Ryan-Parker  version 5.1 according to BrowserStack

**Comment by Ryan-Parker** [comment]
@ZambiBambi The most current version is 8. Lets only test on the 2 most recent versions of all browsers.

**Comment by L8D** [comment]
Also this should've been fixed by 56b4e2a anyways.

**Comment by ZambiBambi** [comment]
@Ryan-Parker I found out that was only for windows based safari, mac based safari is version 8, should i start just testing on mac based or do both ?

**Comment by Ryan-Parker** [comment]
@ZambiBambi Ah makes sense please do both, label the issues accordingly, and include items in the QA fixes document as you've been doing

**Comment by L8D** [comment]
@ZambiBambi Browserstack should allow you to test OS X safari IIRC

**Comment by ZambiBambi** [comment]
@Ryan-Parker Okay thanks 

@L8D  yes it does allow that, i was just wondering if both windows and mac safari should be tested

**Comment by Ryan-Parker** [comment]
@ZambiBambi Sorry for the confusion, but don't worry about windows safari. The percentage of users is extremely low. Still worry about the cross over for Firefox & Chrome though.

**Comment by ZambiBambi** [comment]
@Ryan-Parker  i thought that would be the case, will do that
