### ISSUE TITLE
UX of Task Input

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#163]
1. When the user clicks in the task area and presses enter it should add the item to the list 
2. When the user presses enter in the timer area it should exit the timer similarly to pressing tab
3. Pencil Icon on the timer to indicate that it is editable 
4. Hitting Tab while in the timer input should reflect the new time

**Comment by Ryan-Parker** [comment]
@GarrethDottin Can we also add the issue here that when you tab into the timer input and input a new time and hit tab again the new time is not reflected.

**Comment by garrethdev** [comment]
@Ryan-Parker yea I agree it would help the ux flow

**Comment by garrethdev** [comment]
Pencil icon should be centered and below the main text

**Comment by ZambiBambi** [comment]
Cant press enter in Firefox to add the task to the list

**Comment by ZambiBambi** [comment]
Can start a task without a task name as well (all browsers)

**Comment by garrethdev** [comment]
@ZambiBambi yea the second issue is actually expected behavior we want to accommodate for users who want use the timer without a task. But we definitely need to fix the first with Firefox.
