### ISSUE TITLE
Notifications for Onboarding

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#164]
The first time the user logs into the system, they should see onboarding notifications. The onboarding notifications should reflect the designs on invision. 

Image: 
https://projects.invisionapp.com/share/422BZ1OQ7#/screens/77727566

Content: 
https://docs.google.com/document/d/1bsLxIfwh0WZXLIW3_tTOndevAUlAiRMOfNZpSoUsdBM/edit#

Additional Resources: 
http://codyhouse.co/demo/product-tour/index.html#0

**Comment by Ryan-Parker** [comment]
@L8D The final notification for Share It should say "Finish" not "Next"

**Comment by Ryan-Parker** [comment]
@L8D I also noticed that when you finish the on boarding you can no longer get out of the selected state of the timer. See screenshot below: 

![screen shot 2015-07-21 at 1 36 18 pm](https://cloud.githubusercontent.com/assets/7152379/8807941/9a5998b4-2fad-11e5-9929-f134930c70d8.png)

**Comment by garrethdev** [comment]
-Sizing of button needs to be fixed
-Last state should say finished
