### ISSUE TITLE
Social Panel > Responsive Layout Broken

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#197]
The responsive layout is broken on the social panel: 

![screen shot 2015-07-24 at 12 24 52 am](https://cloud.githubusercontent.com/assets/7152379/8867673/6f221aec-319a-11e5-90a1-1e328009c9d2.png)

**Comment by ZambiBambi** [comment]
Still a problem
![bs_macyos_safari_8 0 3](https://cloud.githubusercontent.com/assets/13108339/9221008/1838f8c8-412a-11e5-8687-7a708e557498.jpg)
