### ISSUE TITLE
Can't edit timer 

### ISSUE THREAD

**Issue by ZambiBambi** [GrooveOtter/grooveotter-client#204]
Can't select into the timer to edit the time

**Comment by L8D** [comment]
Also can't reproduce on an iPhone 6 in Safari

**Comment by Ryan-Parker** [comment]
Just tested on my phone. The timer, archive, and share this task selector is not selectable in Safari on iPhone. Are you using a simulator?

Sent from my iPhone

> On Aug 8, 2015, at 4:36 PM, Tenor Biel notifications@github.com wrote:
> 
> Also can't reproduce on an iPhone 6 in Safari
> 
> —
> Reply to this email directly or view it on GitHub.

## 

HZ                    branding. advertising. digital. integrated. 
DC METRO     10101 molecular drive, suite 300, rockville, maryland 20850 | 
301-294-6302 
NEW YORK     298 fifth avenue, 2nd floor, new york, new york 10001 |  
646-454-9206
BALTIMORE   1429 aliceanna street, 3rd floor, baltimore, maryland 21231 | 
443-990-1834
hzdg.com | facebook.com/hzdg  | follow us @hzdg https://twitter.com/hzdg

**Comment by L8D** [comment]
@Ryan-Parker Are you on an iPhone 5S? When I tested it out I noticed there was a delay, and it tooks a few taps in order for it to register, but it did eventually open up the selector. The archive tab and share box both worked fine for me.

**Comment by Ryan-Parker** [comment]
I am on an iPhone 6 right now and was it able to select any of the items. I can on chrome on my iPhone however 

Sent from my iPhone

> On Aug 8, 2015, at 11:16 PM, Tenor Biel notifications@github.com wrote:
> 
> @Ryan-Parker Are you on an iPhone 5S? When I tested it out I noticed there was a delay, and it tooks a few taps in order for it to register, but it did eventually open up the selector. The archive tab and share box both worked fine for me.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

HZ                    branding. advertising. digital. integrated. 
DC METRO     10101 molecular drive, suite 300, rockville, maryland 20850 | 
301-294-6302 
NEW YORK     298 fifth avenue, 2nd floor, new york, new york 10001 |  
646-454-9206
BALTIMORE   1429 aliceanna street, 3rd floor, baltimore, maryland 21231 | 
443-990-1834
hzdg.com | facebook.com/hzdg  | follow us @hzdg https://twitter.com/hzdg

**Comment by L8D** [comment]
Sorry for the cruddy quality, but here is a recording of me exercising these features: [https://youtu.be/3VzoGQvtq6U](https://youtu.be/3VzoGQvtq6U). I'm thinking either an update to Safari is breaking things, or your version of Safari is out of date.

**Comment by Ryan-Parker** [comment]
Hm yeah I see. Can you use browser stack to check for the other versions of safari? I'm sure this is a fairly common issue as it's rare someone updates their Safari on mobile 

Sent from my iPhone

> On Aug 8, 2015, at 11:29 PM, Tenor Biel notifications@github.com wrote:
> 
> Sorry for the cruddy quality, but here is a recording of me exercising these features: https://youtu.be/3VzoGQvtq6U. I'm thinking either an update to Safari is breaking things, or your version of Safari is out of date.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

HZ                    branding. advertising. digital. integrated. 
DC METRO     10101 molecular drive, suite 300, rockville, maryland 20850 | 
301-294-6302 
NEW YORK     298 fifth avenue, 2nd floor, new york, new york 10001 |  
646-454-9206
BALTIMORE   1429 aliceanna street, 3rd floor, baltimore, maryland 21231 | 
443-990-1834
hzdg.com | facebook.com/hzdg  | follow us @hzdg https://twitter.com/hzdg

**Comment by L8D** [comment]
@Ryan-Parker Everything works with the latest versions, but when I tested on an iPhone 5S with iOS 7 it seems nothing works.

**Comment by Ryan-Parker** [comment]
That could be a lingering issue for my
Phone as well. Can you look into a fix for that?

On Saturday, August 8, 2015, Tenor Biel notifications@github.com wrote:

> @Ryan-Parker https://github.com/Ryan-Parker Everything works with the
> latest versions, but when I tested on an iPhone 5S with iOS 7 it seems
> nothing works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GrooveOtter/grooveotter-client/issues/204#issuecomment-129101872
> .

## 

RYAN PARKER | PROJECT MANAGER
ryanp@hzdg.com | 301.294.6302 ext. 2467

## 

HZ                    branding. advertising. digital. integrated. 
DC METRO     10101 molecular drive, suite 300, rockville, maryland 20850 | 
301-294-6302 
NEW YORK     298 fifth avenue, 2nd floor, new york, new york 10001 |  
646-454-9206
BALTIMORE   1429 aliceanna street, 3rd floor, baltimore, maryland 21231 | 
443-990-1834
hzdg.com | facebook.com/hzdg  | follow us @hzdg https://twitter.com/hzdg

**Comment by Ryan-Parker** [comment]
@L8D This seems to be resolved from last pull

**Comment by Ryan-Parker** [comment]
@L8D This seems to be broken again
