### ISSUE TITLE
Task Layout Broken

### ISSUE THREAD

**Issue by ZambiBambi** [GrooveOtter/grooveotter-client#206]
![img_0569](https://cloud.githubusercontent.com/assets/13108339/8921032/33393b50-3514-11e5-9644-e22f72f7ab4d.PNG)
![img_0567](https://cloud.githubusercontent.com/assets/13108339/8921031/33381f90-3514-11e5-83b7-67c6e0168dbe.PNG)

**Comment by Ryan-Parker** [comment]
@L8D This is something we may need to discuss further, as everything needs to be in line but we might need to figure out a solution depending on the constraints.

**Comment by L8D** [comment]
@Ryan-Parker I went ahead and just expanded out the task in the list for mobile devices
![task list example](https://cloud.githubusercontent.com/assets/2355315/9152216/18098b58-3de5-11e5-8081-8c62a1caaf55.png)

**Comment by Ryan-Parker** [comment]
@L8D I think we need to take another look at this solution.
