### ISSUE TITLE
News feed text cut off

### ISSUE THREAD

**Issue by ZambiBambi** [GrooveOtter/grooveotter-client#208]
Its mainly cut off in portrait view but if the line of text is long enough it will be cut off in landscape view

Portrait View
![img_0568](https://cloud.githubusercontent.com/assets/13108339/8928214/315e8546-3560-11e5-9856-41d500c26a44.PNG)

Landscape View
![img_0686](https://cloud.githubusercontent.com/assets/13108339/8928274/9ad10a80-3560-11e5-8269-4b1db3a9f3c5.PNG)

**Comment by GarrethDottin** [comment]
@ZambiBambi was this in safari?

**Comment by ZambiBambi** [comment]
both safari and chrome, all issues tested on iPhone are on both.

**Comment by Ryan-Parker** [comment]
@ZambiBambi Please apply appropriate browser tags to the issues so @L8D knows which browsers these issues happen on.

**Comment by ZambiBambi** [comment]
@Ryan-Parker Okay can do that, i didnt think it was a problem though because there is only 2 browsers that are used on iPhone and both tested the same bugs consistently.

**Comment by Ryan-Parker** [comment]
@ZambiBambi No problem its just we will not know that both tested consistently or not

**Comment by Ryan-Parker** [comment]
@L8D Still see this in some cases. Lets allow for 3 lines of copy. 

![image1 19](https://cloud.githubusercontent.com/assets/7152379/9182060/6f774398-3f76-11e5-8cf5-63df5270e303.PNG)
