### ISSUE TITLE
Starting the Time

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#21]
When you are in the edit phase, you should be able to start the timer by pressing enter or clicking one of the preset input buttons. 

Criteria: 
1. User clicking presets or pressing enter starts the timer

**Comment by L8D** [comment]
Sorry to nitpick you, but could you remove the "Timer Feature >" prefix
from issues and instead include those issues in a shared "Timer" milestone?

**Comment by garrethdev** [comment]
Yea I wanna do milestones a bit different than we have them, it will be by week the milestones. So for this week's its getting the main dashboard done.

**Comment by L8D** [comment]
Duplicate of #13
