### ISSUE TITLE
Archived Tasks Not Aligned Correctly 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#212]
![screen shot 2015-07-28 at 11 13 26 pm](https://cloud.githubusercontent.com/assets/7152379/8949220/5f8b280c-357e-11e5-8c04-35d4354a2c6c.png)

**Comment by L8D** [comment]
@Ryan-Parker do you feel like there needs to be more space between the date and the count section? How do you envision this should look on smaller screens?

**Comment by Ryan-Parker** [comment]
@L8D What if we remove the text "task complete" for mobile breakpoints so that it just has the number and then that number can be in line. 

We will still need to address this issue with longer tasks though. We may need to truncate those.
