### ISSUE TITLE
Site should be fixed within viewport

### ISSUE THREAD

**Issue by ZambiBambi** [GrooveOtter/grooveotter-client#213]
On mobile you can scroll horizontally. Instead the site should be fixed within the viewport and only vertical scrolling should be allowed. 
![image](https://cloud.githubusercontent.com/assets/13108339/8949418/639e26ba-35f6-11e5-9fd8-a5b006ae12f7.jpg)

**Comment by L8D** [comment]
@ZambiBambi is this still occuring?

**Comment by ZambiBambi** [comment]
@L8D Yes it's still a problem
