### ISSUE TITLE
Video Not Showing

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#216]
The product video does not show on FF 

![screen shot 2015-07-30 at 12 28 22 pm](https://cloud.githubusercontent.com/assets/7152379/8988820/7ef3b072-36b6-11e5-857e-18a077f26afa.png)

**Comment by L8D** [comment]
This is because the video is in .mov and not .mp4

**Comment by Ryan-Parker** [comment]
We have resolved this issue should be closed

Sent from my iPhone

> On Aug 8, 2015, at 11:13 PM, Tenor Biel notifications@github.com wrote:
> 
> This is because the video is in .mov and not .mp4
> 
> —
> Reply to this email directly or view it on GitHub.

## 

HZ                    branding. advertising. digital. integrated. 
DC METRO     10101 molecular drive, suite 300, rockville, maryland 20850 | 
301-294-6302 
NEW YORK     298 fifth avenue, 2nd floor, new york, new york 10001 |  
646-454-9206
BALTIMORE   1429 aliceanna street, 3rd floor, baltimore, maryland 21231 | 
443-990-1834
hzdg.com | facebook.com/hzdg  | follow us @hzdg https://twitter.com/hzdg
