### ISSUE TITLE
Setup Mouseflow

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#225]
`<script type="text/javascript">
        var _mfq = _mfq || [];
        (function () {
        var mf = document.createElement("script"); mf.type = "text/javascript"; mf.async = true;
        mf.src = "//cdn.mouseflow.com/projects/6f6f962c-6a5d-4a53-8014-c714fa10a594.js";
        document.getElementsByTagName("head")[0].appendChild(mf);
      })();
    </script>`

**Comment by L8D** [comment]
Closed by 4683e404b03c326a0e9a12be51e9b260ab19bb78
