### ISSUE TITLE
Newsfeed not showing names (2)

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#259]
Current Behavior: 
In the current system, at times names are not displayed. This is not consistent behavior. 
<img width="498" alt="screen shot 2015-09-14 at 3 40 05 pm" src="https://cloud.githubusercontent.com/assets/5047981/9859752/01133f38-5af6-11e5-9ba5-41f5c01fb186.png">

Expected Behavior: 
The bug causing the full_name to not being displayed should be fixed it, a name should always be sent to the client in the backbone model.

**Comment by L8D** [comment]
This looks like a `withRelated({})` call is missing the information on the user, but I'm guessing that's not the actual case since the image is being read fine.

**Comment by garrethdev** [comment]
@L8D should this be on the index call on the Tasks item? And why would it sometimes return the full_name and not other times?
