### ISSUE TITLE
Master Branch on Github should point to staging (1) 

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#260]
Current Behavior: 
In the current system when you push from master it goes directly to grooveotter.com. The current staging environment is not used. 

Expected Behavior: 
There should be a separate environment when a ticket is ready to merge it should be merged into master but master should point to gotr-staging. When a ticket passes QA on staging at the end of the one or two week sprint it will be pushed from Gotr-Staging to production. Production should be a separated branch that is hooked to the current Grooveotter.com website.

**Comment by Ryan-Parker** [comment]
Can you also apply a high priority tag to the issue. It will make it easier
for the dev to see what he needs to do first.

On Mon, Sep 14, 2015 at 4:24 PM, GarrethDottin notifications@github.com
wrote:

> Current Behavior:
> In the current system when you push from master it goes directly to
> grooveotter.com. The current staging environment is not used.
> 
> Expected Behavior:
> There should be a separate environment when a ticket is ready to merge it
> should be merged into master but master should point to gotr-staging. When
> a ticket passes QA on staging at the end of the one or two week sprint it
> will be pushed from Gotr-Staging to production. Production should be a
> separated branch that is hooked to the current Grooveotter.com website.
> 
> Priority:
> High
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GrooveOtter/grooveotter-client/issues/260.

## 

RYAN PARKER | PROJECT MANAGER
ryanp@hzdg.com | 301.294.6302 ext. 2467

## 

HZ                    branding. advertising. digital. integrated. 
DC METRO     10101 molecular drive, suite 300, rockville, maryland 20850 | 
301-294-6302 
NEW YORK     298 fifth avenue, 2nd floor, new york, new york 10001 |  
646-454-9206
BALTIMORE   1429 aliceanna street, 3rd floor, baltimore, maryland 21231 | 
443-990-1834
BAY AREA       725 front street, suite 206, santa cruz, california 95060 | 
831-421-9017
hzdg.com | facebook.com/hzdg  | follow us @hzdg https://twitter.com/hzdg

**Comment by garrethdev** [comment]
@Ryan-Parker  Ill go over more in depth tomorrow the idea of the system. But the numbers correspond to what should be addressed first

**Comment by L8D** [comment]
@GarrethDottin I just switched the deployment from grooveotter-demo to gotr-staging. You can see this [here](https://dashboard.heroku.com/pipelines/18f6dd1d-3676-4c40-b6df-b21f6578da93).

To go from staging to production, you just need to hit the "promote to production" button.
