### ISSUE TITLE
Fix NaN:NaN problem with timer

### ISSUE THREAD

**Issue by ghost** [GrooveOtter/grooveotter-client#27]
1. Edit the timer and input 600. Press Enter in the box.
2. Click Start task.
3. Edit the timer again but do not input anything. Press Enter in the box.

Output: NaN:NaN shown on timer.

![image](https://cloud.githubusercontent.com/assets/5413424/7122535/192d6d8a-e1ea-11e4-8e22-e779ac604a7e.png)

**Comment by L8D** [comment]
Nice find. Thanks.

**Comment by L8D** [comment]
I'm not sure when, but it appears like this bug has been fixed.
