### ISSUE TITLE
Timer arrow clicks take user out of edit mode

### ISSUE THREAD

**Issue by ghost** [GrooveOtter/grooveotter-client#44]
1. Double click the timer.
2. Attempt to click the up arrow to increase the duration by a minute.
3. Repeat Step 2 a few times quickly.

Output: It increases the time by only 2 minutes and leaves edit mode.

Note: This happens for both arrows.

Browser: Chrome

**Comment by L8D** [comment]
This is because chrome thinks you're double-clicking. I'm not sure how I'm going to fix this.

**Comment by garrethdev** [comment]
@L8D We should be removing the arrows so that issue should solve itself.
