### ISSUE TITLE
Exiting timer input view should display form errors

### ISSUE THREAD

**Issue by ghost** [GrooveOtter/grooveotter-client#45]
1. In Edit mode for the timer, enter '1 hour'
2. Exit Edit mode by double clicking.

Output: NaN:NaN is shown for the time.

Note: If for step 2, we simply press Enter, we are shown an error 'Please enter a number." Would it be possible to get that error message if I double click off the edit mode for the timer?
![2015-04-21 22_30_59-grooveotter](https://cloud.githubusercontent.com/assets/5413424/7266355/31b17a62-e876-11e4-8d62-18247f2c89b9.png)

![2015-04-21 22_32_26-grooveotter](https://cloud.githubusercontent.com/assets/5413424/7266365/5f1157ac-e876-11e4-8bfc-d368ffc22337.png)

**Comment by L8D** [comment]
Nice catch on the inconsistency
