### ISSUE TITLE
Working time not updating

### ISSUE THREAD

**Issue by ghost** [GrooveOtter/grooveotter-client#47]
1. Start a task and wait a minute.

Output: The working time does not change.

Late edit: Okay I think I didn't understand that the working time only change when I complete the task. I thought it would be an ongoing count.

![2015-04-21 22_43_07-grooveotter](https://cloud.githubusercontent.com/assets/5413424/7266453/d2f40df8-e877-11e4-8e40-33feee7050d2.png)

**Comment by L8D** [comment]
I thought @GarrethDottin said the times should only update when the user completes a task.

**Comment by garrethdev** [comment]
@JVeerman @L8D yea it should only tie to when the user is finished with a task
