### ISSUE TITLE
Completed > Should not show if no content

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#56]
If there is no task completed the completed area should not be present

![screen shot 2015-04-30 at 5 57 57 pm](https://cloud.githubusercontent.com/assets/7152379/7423378/841547be-ef62-11e4-89b0-cc217839ae05.png)

**Comment by L8D** [comment]
This was the behavior before. The lingering 'Completed' section was because I was being lazy. The completed section has been removed from the 'Today' view for the time being.
