### ISSUE TITLE
The active task should be selected

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#57]
When a task is in progress that task should always be selected and showing the "in progress" button. 

Current: 
![screen shot 2015-04-30 at 5 55 51 pm](https://cloud.githubusercontent.com/assets/7152379/7423339/4792c442-ef62-11e4-9e3d-72904444037b.png)

Expected: 
![screen shot 2015-04-30 at 5 57 08 pm](https://cloud.githubusercontent.com/assets/7152379/7423354/5a84b150-ef62-11e4-996e-6bc2ee852571.png)

**Comment by L8D** [comment]
![problem](https://cloud.githubusercontent.com/assets/2355315/7927960/88851f22-08ad-11e5-8784-ba7bf295eb55.png)

**Comment by Ryan-Parker** [comment]
@GarrethDottin What's your opinion of this?

**Comment by garrethdev** [comment]
@Ryan-Parker @L8D  it doesn't seem avoidable to me. I think we keep it that when your in progress its always highlighted. Its a good reminder for someone when they come back to the app.

**Comment by Ryan-Parker** [comment]
@GarrethDottin I agree with the sentiment. Lets move forward with the functionality intended by the spec.
