### ISSUE TITLE
Today Task > Does not show the full task

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#58]
The task gets cut off and does not extend to the edge of the start button: 

![screen shot 2015-04-30 at 5 54 14 pm](https://cloud.githubusercontent.com/assets/7152379/7423311/08844d66-ef62-11e4-9417-58b73aa1c914.png)

![screen shot 2015-04-30 at 5 54 27 pm](https://cloud.githubusercontent.com/assets/7152379/7423314/0ceec14c-ef62-11e4-96a5-142cc23764df.png)

**Comment by L8D** [comment]
Yeah... Foundation sucks... This is mostly fixed in the recent updates
