### ISSUE TITLE
Completed Tasks > Shows in both "Completed" and "Today" area

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#59]
![screen shot 2015-04-30 at 5 52 32 pm](https://cloud.githubusercontent.com/assets/7152379/7423273/c767bd68-ef61-11e4-81ba-f6cf2d4fffa3.png)

**Comment by L8D** [comment]
Same problem as before, I had changed things with the task list view. Fixed now due to the changes which involved removing the completed section all together.
