### ISSUE TITLE
Implement Archive UI

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#62]
UI should match specs

Criteria: 
1. User can cycle through weeks 
2. User can see time associated with tasks 
3. User can see tasks associated with a week

**Comment by garrethdev** [comment]
[Updated]Implement Icons on the Archive

**Comment by garrethdev** [comment]
Archive doesnt save tasks,  if user adds task in task bar and marks it as complete it wont show up in the Archive.
Original State: 
![screen shot 2015-05-13 at 9 48 27 pm](https://cloud.githubusercontent.com/assets/5047981/7624607/9f011826-f9b9-11e4-9dfc-f67d3b0e7d3b.png)

After Completing Task: 
![screen shot 2015-05-13 at 9 48 38 pm](https://cloud.githubusercontent.com/assets/5047981/7624612/b49cecf0-f9b9-11e4-87dc-b9cfd3d61e75.png)

**Comment by L8D** [comment]
Cannot reproduce...

**Comment by garrethdev** [comment]
Bug Fixed Still missing icons associated with archive

In Production: 
![screen shot 2015-05-17 at 1 25 35 pm](https://cloud.githubusercontent.com/assets/5047981/7671309/d2742a6e-fc97-11e4-88cf-8db28c496ffd.png)

**Comment by L8D** [comment]
Should be there now
