### ISSUE TITLE
Removing tasks from task list should not have an animation

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#63]
Currently removing a task from the list has the animation of checking a task off ones list. Remove this it should be instantaneous and how it was before.

**Comment by L8D** [comment]
paging @GarrethDottin 
If you're referring to the checkoff animation then you and Garreth need to talk about UI behavior more often.

**Comment by garrethdev** [comment]
@Ryan-Parker  @L8D  This ticket has already been created in a milestone and will be closed

**Comment by Ryan-Parker** [comment]
@GarrethDottin @L8D I do not see a redundant ticket for this. Can you reference here with duplicate if I have missed. The point of this was that when you delete a task there is no need for animation as the animation is more of a reward. 

Let me know thoughts if you feel otherwise.

**Comment by L8D** [comment]
Garreth created #49, and that's why there is an animation now.

**Comment by L8D** [comment]
Are you saying there should be an animation for completing a task but not for destroying one?

**Comment by Ryan-Parker** [comment]
@L8D That is correct. Hitting X to "destroy" a task should not have an animation. It should just remove it from your list.

**Comment by L8D** [comment]
@Ryan-Parker this is way more difficult to do than you might think but ok.
