### ISSUE TITLE
In Progress Task > User should not be able to edit

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#68]
Nothing should be editable (the task or time) when a task is in progress

**Comment by Ryan-Parker** [comment]
@L8D This is still an issue. The user can edit the top task area when a task is in progress

![screen shot 2015-05-01 at 2 27 39 pm](https://cloud.githubusercontent.com/assets/7152379/7435074/3e26dd74-f00e-11e4-9d12-72cd31d85468.png)

**Comment by L8D** [comment]
The user can't edit the active task from the task list, but editing the task name in the task-name field was expected behavior at one point

**Comment by L8D** [comment]
I guess I'll fix this anyways
