### ISSUE TITLE
Controllers should be documented

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#77]
In our push towards better documentation and onboarding for new developers, we need to start documenting with controllers. 

Criteria:
The controllers should have js-doc explaining inputs and the purpose of each function.

**Comment by L8D** [comment]
Notes for me for later:
- Stores should be renamed to Controllers
- Components should renamed to Views
- 'scripts' should be renamed to 'app'
- 'styles' should be renamed to 'css'
