### ISSUE TITLE
Landing Page UI

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#78]
The Landing Page should reflect the specs. 

Criteria: 
1. Finish the 6 Panels
2. Add in animations specified in the documentation

**Comment by L8D** [comment]
Things left to do:
- Setup jQuery (not Zepto) and the jQuery.appear plugins
- Configure down chevron to smooth scroll page using jQuery
- Implement carousel paging system with jQuery
- Animate carousel
- Create footer and call-to-action section
- Go over small color and spacing details with Natalie

**Comment by Ryan-Parker** [comment]
@L8D I'd like to keep open until #104 has been resolved. I view that as the last UI touch up until we tackle responsive.

**Comment by L8D** [comment]
@Ryan-Parker by responsive, do you mean the changes to the dashboard to make it mobile-friendly? The vast majority of the landing page seamlessly scales down to mobile.

**Comment by Ryan-Parker** [comment]
@L8D Yes I was talking about mobile responsiveness and we ended up tackling all those issues last week.
