### ISSUE TITLE
Archive Not Functioning 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#79]
When I check a task off my list it will sometimes show the full task in the "archive" similar to how it is displayed in "today" or just not show it at all. The behavior is inconsistent. 

![screen shot 2015-05-14 at 10 06 14 am](https://cloud.githubusercontent.com/assets/7152379/7633247/08d61af0-fa21-11e4-8e0b-765d38dfb4c9.png)

![screen shot 2015-05-14 at 10 12 29 am](https://cloud.githubusercontent.com/assets/7152379/7633399/c32dde92-fa21-11e4-8632-50ce8d4f393c.png)

**Comment by L8D** [comment]
This is not a bug. The app behaves like this when the API server is not running (i.e. has crashed).
