### ISSUE TITLE
Arrows & Date Size Should Match Spec 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#86]
Design: 

![screen shot 2015-05-18 at 1 34 22 pm](https://cloud.githubusercontent.com/assets/7152379/7686382/69545cee-fd63-11e4-896a-a580dbe77465.png)

Demo: 

![screen shot 2015-05-18 at 1 34 32 pm](https://cloud.githubusercontent.com/assets/7152379/7686388/751b9c4a-fd63-11e4-823a-ebe15f77c88b.png)

**Comment by L8D** [comment]
Arrow size is closer to the wireframes now, although I'm unsure whether you want to stick with the large button sizes or have a smaller amount of padding.

**Comment by garrethdev** [comment]
Yea It should have less padding and match the thickness of the arrows a bit closer
