### ISSUE TITLE
Secondary Login UI

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#89]
We need to store the email address for twitter users, a separate page will be needed for this.

**Comment by garrethdev** [comment]
Fixes are still needed for this page: 
-Add in clear input Field
-Change GrooveOtter Logo 
-Add in button to save input

**Comment by Ryan-Parker** [comment]
We will also need to update the language for the email signup. @GarrethDottin  and I will be discussing this.

**Comment by Ryan-Parker** [comment]
@L8D What is the URL for this?

**Comment by L8D** [comment]
@Ryan-Parker https://grooveotter-demo.herokuapp.com/signup-twitter

Other than the removal of the link in the logo and any changes to the wording, it should be done

**Comment by Ryan-Parker** [comment]
@L8D Its looking good. The one thing I noticed is there is no error state. Please reference the style guide for that. 

https://projects.invisionapp.com/share/XY2V9XWF9#/screens/72267451?maintainScrollPosition=false

**Comment by garrethdev** [comment]
@L8D 
Few changes to the text. 
Title: Please provide your email address 
Text: Unfortunately Twitter doesn't give us access to your email address.

**Comment by Ryan-Parker** [comment]
@GarrethDottin I'm not sure I like that text. Seems like we are really pushing to collect their email. I think we just say "Please provide your email address" and remove the extra text its unnecessary.

**Comment by garrethdev** [comment]
@Ryan-Parker I think its pretty necessary actually because its already a hassle to have a second login. Enough people will wonder why they are having to go through a second sign up, it instills more trust if we explain why. Im open to a better second sentence though.
