### ISSUE TITLE
First Panel Should Size to Screen

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#92]
The first panel should size correctly to the screen size. This is to ensure the down arrow is ever present. 

Current: 
![screen shot 2015-05-26 at 9 37 03 pm](https://cloud.githubusercontent.com/assets/7152379/7826978/86daf2c2-03ef-11e5-939f-b4fbee617b37.png)

Expected: 
![screen shot 2015-05-26 at 9 38 29 pm](https://cloud.githubusercontent.com/assets/7152379/7826981/97aa7ac8-03ef-11e5-9e61-41817ff63a64.png)

**Comment by L8D** [comment]
Having a static size for the image solves many, many issues with CSS. What I can do is to anchor the downward arrow to the bottom of the screen when the viewport is too small

**Comment by Ryan-Parker** [comment]
@L8D Lets give it a try and see how it looks. I worry on very small screen sizes the text arrow will be too close to the button visually.

**Comment by L8D** [comment]
You'll notice on mobile, if the URL-bar decides to go away when the first panel is still in view, then the background image will resize to accommodate for the new screen space. In my opinion, it looks a bit tacky. There's nothing I can really do about that other than hand-picking heights for specific ranges of viewport sizes (which doesn't even completely solve the issue).

**Comment by Ryan-Parker** [comment]
@L8D I think thats a smaller use case and is okay. But I am noticing the text and button is off now on Mobile. 

![image1 16](https://cloud.githubusercontent.com/assets/7152379/7971887/20123596-0a16-11e5-97ab-fd661202880a.PNG)

**Comment by L8D** [comment]
strange... http://caniuse.com/#feat=flexbox
