### ISSUE TITLE
Panel Animations Should Be Sooner

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#94]
The left and right sweep in animations for panels 3 and 4 should happen slightly sooner as the user scrolls down the page. Right now if a user scrolls quickly they will miss the animation. 

![screen shot 2015-05-26 at 9 43 39 pm](https://cloud.githubusercontent.com/assets/7152379/7827038/4fa43a38-03f0-11e5-9449-01cb47c4bb0b.png)
![screen shot 2015-05-26 at 9 43 45 pm](https://cloud.githubusercontent.com/assets/7152379/7827037/4fa36702-03f0-11e5-9984-6a1a71f4d1c6.png)

**Comment by L8D** [comment]
I've removed the offset and sped up the animations. Until I can get around to importing custom animations from jQuery UI, we're stuck with the default 'swing' animation of jQuery, which I blame for this.
