### ISSUE TITLE
Footer Content Should Be Centered 

### ISSUE THREAD

**Issue by Ryan-Parker** [GrooveOtter/grooveotter-client#95]
Current: 
![screen shot 2015-05-26 at 9 44 56 pm](https://cloud.githubusercontent.com/assets/7152379/7827055/86e747b0-03f0-11e5-9b99-e088219e05cc.png)

**Comment by L8D** [comment]
It’s is not centered in the wireframes

**Comment by Ryan-Parker** [comment]
@L8D Lets center anyway

**Comment by L8D** [comment]
You’re the boss.
